version: "1.0"
services:
  mysql:
    container_name: mysqlapache
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
    networks:
      - apache
    ports:
      - "3306:3306"
    image: "mysql"
    volumes:
      - C:\Users\antho\OneDrive\Documents\mysqlpersist:/var/lib/mysql

  apache:
    depends_on:
      - mysqlapache
    container_name: nginxphp
    networks:
      - apache
    ports:
      - "8080:80"
    image: damienpm/php-apache-mysqli
    volumes:
      - C:\apache:/var/www/html/

networks:
  apache:


